### ISSUE TITLE
Wormate extensions (i.e. Worm World, Wormate Friends Connect, etc.) is not working with this running.

### ISSUE THREAD

**Issue by pere-supremacy** [MatasGrisius/wormate.io-zoom-hack#1]
Hi, I got interested in your code, though there was a problem with running another extension as your code runs and acts like it is an extension, therefore it is blocking other wormate extensions from running.

**Comment by MatasGrisius** [comment]
Hi, thank you for your inquiry.
This code is only suitable for current version of the game assuming no external plugins or extensions are used.

**Comment by Orange319** [comment]
@MatasGrisius Your "wormate.io-zoom-hack" you are doing very well But when your code works It will block all other extensions. want you to fix I'm happy to support And fix it to work in all browsers, especially opera and chrome. Thank you very much.

**Comment by MatasGrisius** [comment]
Could you provide more information:
What extension do you use together with workmate.
What exactly doesn't work and what exactly happens.
Error information in text or photo/video format would also help.

**Comment by Orange319** [comment]
> 

1.It's the game extension not working when using your code.
2. Your code doesn't work in opera and chrome browsers.
3. I don't know what picture to bring to you. because it doesn't work
4. Do you have a private chat? I'm interested in your code.

**Comment by Orange319** [comment]
I want you to fix the zoom code. To be compatible with other extensions of
the game worm. And it can be used in browsers, opera and google chrome. Can
you do it for me? or how much will be charged

ในวันที่ อ. 8 พ.ย. 2022 00:32 น. Matas Grišius ***@***.***>
เขียนว่า:

**Comment by Orange319** [comment]
Thank you very much. You are very kind. I use it together with this add-on
"WormWorld Connect".
I thank you again from the bottom of my heart.🙏🥰🤟❤😊

ในวันที่ พ. 9 พ.ย. 2022 เวลา 03:34 Matas Grišius ***@***.***>
เขียนว่า:

**Comment by Orange319** [comment]
Thank you very much. You are very kind. I use it together with this
extension "WormWorld Connect".
I thank you again from the bottom of my heart.🙏🥰🤟❤😊
And I use .json files through this extension "User JavaScript and CSS".

ในวันที่ พ. 9 พ.ย. 2022 เวลา 03:34 Matas Grišius ***@***.***>
เขียนว่า:

**Comment by MatasGrisius** [comment]
Fixed.
