### ISSUE TITLE
Script no longer works

### ISSUE THREAD

**Issue by JacOliver9000** [MatasGrisius/wormate.io-zoom-hack#4]
The scripts seems to be no longer working since the 'Christmas' update.
Would be great if the script can be updated.

**Comment by MatasGrisius** [comment]
I'll look into it.

**Comment by teddykardos** [comment]
+1 :(

**Comment by Durrah88** [comment]
> I'll look into it.

Hi Matas. any updates on this script?

**Comment by MatasGrisius** [comment]
Fixed.
